[metadata]
name = "tldr"
description = "Browse and preview TLDR help pages"
requirements = ["tldr"]

[source]
command = "tldr --list"

[preview]
command = "tldr '{0}'"

[ui]
preview_panel = { size = 60 }

[actions.open]
description = "Open TLDR page in pager"
command = "tldr '{}'"
mode = "fork"
command = "tldr '{0}'"

[keybindings]
enter = "actions:open"
