set -x fish_color_autosuggestion 555\x1eyellow
set -x fish_color_command d7d7d7
set -x fish_color_comment red
set -x fish_color_cwd green
set -x fish_color_cwd_root red
set -x fish_color_error red\x1e\x2d\x2dbold
set -x fish_color_escape cyan
set -x fish_color_history_current cyan
set -x fish_color_host ffaf5f
set -x fish_color_match cyan
set -x fish_color_normal normal
set -x fish_color_operator cyan
set -x fish_color_param 00afff\x1ecyan
set -x fish_color_quote brown
set -x fish_color_redirection normal
set -x fish_color_search_match \x2d\x2dbackground\x3dpurple
set -x fish_color_status red
set -x fish_color_user ffff87
set -x fish_color_valid_path \x2d\x2dunderline
set -x fish_pager_color_completion normal
set -x fish_pager_color_description 555\x1eyellow
set -x fish_pager_color_prefix cyan
set -x fish_pager_color_progress cyan
